global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'spawn-webhook'
  routes:
    - match:
        severity: critical
      receiver: 'spawn-webhook'
      continue: true
    - match:
        severity: warning
      receiver: 'spawn-webhook'
      continue: true
    - match:
        severity: info
      receiver: 'spawn-webhook'
      continue: true

receivers:
  - name: 'spawn-webhook'
    webhook_configs:
      - url: 'http://localhost:8080/alertmanager/webhook'
        send_resolved: true
        max_alerts: 0

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance_id']
  - source_match:
      severity: 'warning'
    target_match:
      severity: 'info'
    equal: ['alertname', 'instance_id']
